type Beacon {
  beaconId: ID!
  createdAt: AWSDateTime!
}

type BeaconEvent {
  beaconId: ID!
  eventId: ID!
  type: String!
  pressedBy: ID!
  pressedAt: AWSDateTime!
}

enum DevicePlatform {
  IOS
  ANDROID
}

type Query {
  health: String!
}

type Mutation {
  joinBeacon(code: ID!): Beacon!
  registerDevice(beaconId: ID!, pushToken: String!, platform: DevicePlatform!): Boolean!
  unregisterDevice(beaconId: ID!): Boolean!
  sendBeacon(beaconId: ID!): BeaconEvent!
}

type Subscription {
  onBeaconSent(beaconId: ID!): BeaconEvent
    @aws_subscribe(mutations: ["sendBeacon"])
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
